<?php
declare(strict_types=1);

/*
 * 	Identity switch RoundCube Bundle
 *
 *	@copyright	(c) 2024 - 2026 Florian Daeumling, Germany. All right reserved
 * 	@license 	https://github.com/toteph42/identity_switch/blob/master/LICENSE
 */
$labels = [];

$labels['isw.common.label'] = 'Name der Identität im Auswahlmenü';
$labels['isw.notify.caption'] = 'Neue Nachrichten';
$labels['isw.notify.basic'] = 'Benachrichtigung im Browser bei neuer Nachricht';
$labels['isw.notify.desktop'] = 'Desktop-Benachrichtigung bei neuer Nachricht';
$labels['isw.notify.timeout'] = 'Desktop-Benachrichtigung schließen';
$labels['isw.notify.sound'] = 'Akustische Meldung bei neuer Nachricht';
$labels['isw.notify.test'] = 'Test';
$labels['isw.used.prefs'] = 'Vom identity_switch Plugin verwaltete Einstellungen';
$labels['isw.hide.prefs'] = 'Einstellung werden aufgrund der Plugin-Konfiguration nicht angezeigt.';
$labels['isw.identity'] = 'Identität';
$labels['isw.notify.title'] = 'Neue E-Mails';
$labels['isw.notify.msg'] = '%d für %s';
$labels['isw.notify.err.autoplay'] = 'Kann Musik nicht abspielen!'."\r\n".
					 'Bitte überprüfen Sie die Einstellungen der "Automatische Wiedergabe" für diese Seite in Ihrem Browser.';
$labels['isw.notify.err.notification'] = 'Kann Benachrichtigung nicht senden!.'."\r\n".
					 'Bitte überprüfen Sie die Einstellungen der "Benachrichtigungen" für diese Seite in Ihrem Browser.';
