<?php
declare(strict_types=1);

/*
 * 	Identity switch RoundCube Bundle
 *
 *	@copyright	(c) 2024 - 2026 Florian Daeumling, Germany. All right reserved
 * 	@license 	https://github.com/toteph42/identity_switch/blob/master/LICENSE
 */
$labels = [];

$labels['isw.common.label'] = 'Name of identity in selection box';
$labels['isw.notify.caption'] = 'New messages';
$labels['isw.notify.basic'] = 'Display browser notifications for new messages';
$labels['isw.notify.desktop'] = 'Display desktop notifications for new messages';
$labels['isw.notify.timeout'] = 'Close desktop notification';
$labels['isw.notify.sound'] = 'Play sound for new messages';
$labels['isw.notify.test'] = 'Test';
$labels['isw.used.prefs'] = 'Preferences managed by dentity_switch plugin';
$labels['isw.hide.prefs'] = 'Preferences were hidden according to plugin configuration.';
$labels['isw.identity'] = 'Identity';
$labels['isw.notify.title'] = 'New Emails';
$labels['isw.notify.msg'] = '%d for %s';
$labels['isw.notify.err.autoplay'] = 'Cannot play sound file!'."\r\n".
								 'Please check your "Autoplay" settings for this page in your browser.';
$labels['isw.notify.err.notification'] = 'Cannot send notification!'."\r\n".
									 'Please check your "Notification" settings for this page in your browser.';

