<?php
declare(strict_types=1);

/*
 * Identity switch RoundCube Bundle
 *
 *	@copyright	(c) 2024 - 2026 Florian Daeumling, Germany.
 * Minden jog fenntartva
 * @license 	https://github.com/toteph42/identity_switch/blob/master/LICENSE
 */
$labels = [];

$labels['isw.common.label'] = 'Az identitás neve a kiválasztó mezőben';
$labels['isw.notify.caption'] = 'Új üzenetek';
$labels['isw.notify.basic'] = 'Böngésző értesítések megjelenítése új üzeneteknél';
$labels['isw.notify.desktop'] = 'Asztali értesítések megjelenítése új üzeneteknél';
$labels['isw.notify.timeout'] = 'Asztali értesítés bezárása';
$labels['isw.notify.sound'] = 'Hangjelzés új üzeneteknél';
$labels['isw.notify.test'] = 'Teszt';
$labels['isw.used.prefs'] = 'Preferences managed by dentity_switch plugin';
$labels['isw.hide.prefs'] = 'Preferences were hidden according to plugin configuration.';
$labels['isw.identity'] = 'Azonosító';
$labels['isw.notify.title'] = 'Új e-mailek';
$labels['isw.notify.msg'] = '%d ehhez: %s';
$labels['isw.notify.err.autoplay'] = 'Nem sikerült lejátszani a hangfájlt!'."\r\n".
					'Kérjük, ellenőrizze a böngésző "Automatikus lejátszás" beállításait ennél az oldalnál.';
$labels['isw.notify.err.notification'] = 'Nem sikerült elküldeni az értesítést!'."\r\n".
					'Kérjük, ellenőrizze a böngésző "Értesítés" beállításait ennél az oldalnál.';
