<?php
declare(strict_types=1);

/*
 * 	Identity switch RoundCube Bundle
 *
 *	@copyright	(c) 2024 - 2026 Florian Daeumling, Germany. All right reserved
 * 	@license 	https://github.com/toteph42/identity_switch/blob/master/LICENSE
 */
$labels = [];

$labels['isw.common.label'] = 'Name of identity in selection box';
$labels['isw.notify.caption'] = 'Mesaje noi';
$labels['isw.notify.basic'] = 'Afișează notificări în browser pentru mesaje noi';
$labels['isw.notify.desktop'] = 'Afișează notificări pe desktop pentru mesaje noi';
$labels['isw.notify.timeout'] = 'Închide notificarea desktop';
$labels['isw.notify.sound'] = 'Redă sunet la primirea de mesaje noi';
$labels['isw.notify.test'] = 'Test';
$labels['isw.used.prefs'] = 'Preferences managed by dentity_switch plugin';
$labels['isw.hide.prefs'] = 'Preferences were hidden according to plugin configuration.';
$labels['isw.identity'] = 'Identitate';
$labels['isw.notify.title'] = 'Emailuri noi';
$labels['isw.notify.msg'] = '%d pentru %s';
$labels['isw.notify.err.autoplay'] = 'Fișierul audio nu poate fi redat!'."\r\n".
							'Verifică setările "Autoplay" pentru această pagină în browserul tău.';
$labels['isw.notify.err.notification'] = 'Notificarea nu poate fi trimisă!'."\r\n".
							'Verifică setările "Notificări" pentru această pagină în browserul tău.';
