<?php
declare(strict_types=1);

/*
 * 	Identity switch RoundCube Bundle
 *
 *	@copyright	(c) 2024 - 2026 Florian Daeumling, Germany. All right reserved
 * 	@license 	https://github.com/toteph42/identity_switch/blob/master/LICENSE
 */
$labels = [];

$labels['isw.common.label'] = 'Name of identity in selection box';
$labels['isw.notify.caption'] = 'Новые письма';
$labels['isw.notify.basic'] = 'Показывать уведомления в браузере при новом письме';
$labels['isw.notify.desktop'] = 'Показывать уведомления на рабочем столе при новом письме';
$labels['isw.notify.timeout'] = 'Закрыть уведомление на рабочем столе';
$labels['isw.notify.sound'] = 'Проиграть звук при новом письме';
$labels['isw.notify.test'] = 'Тест';
$labels['isw.used.prefs'] = 'Preferences managed by dentity_switch plugin';
$labels['isw.hide.prefs'] = 'Preferences were hidden according to plugin configuration.';
$labels['isw.identity'] = 'Личность';
$labels['isw.notify.title'] = 'Новые письма';
$labels['isw.notify.msg'] = '%d для %s';
$labels['isw.notify.err.autoplay'] = 'Не могу проиграть звуковой файл!'."\r\n".
					'Пожалуйста, проверьте настройки "Автовоспроизведение" для этой страницы в вашем браузере.';
$labels['isw.notify.err.notification'] = 'Не могу отправить уведомление!'."\r\n".
					'Пожалуйста, проверьте настройки "Уведомление" для этой страницы в вашем браузере.';

